---

- name: Setup packages
  ansible.builtin.include_role:
    name: amtega.packages
  vars:
    packages_os:
      all:
        7:
          libselinux-python3: present
        8:
          python3-libsemanage: present
      fedora:
        all:
          python3-libsemanage: present
