---

- name: Setup packages
  include_role:
    name: amtega.packages
  vars:
    packages_os:
      centos:
        7:
          libselinux-python3: present
        8:
          python3-libsemanage: present
      fedora:
        all:
          python3-libsemanage: present
      redhat:
        7:
          libselinux-python3: present
        8:
          python3-libsemanage: present
