---
# Role tasks

- block:
    - include_tasks: gather.yml

    - block:
        - include_tasks: factory.yml
          when: python_semanage_is_factory_python

        - include_tasks: custom.yml
          when: not python_semanage_is_factory_python
      vars:
        python_semanage_is_factory_python: >-
          {{ python_semanage_python_check_result.stdout
             is search("/usr/bin/python3") }}
             or python_semanage_python_check_result.stdout
                is search("/usr/libexec/platform-python3")
  tags:
    - role::python_semanage
