---
# Role tasks

- name: Setup python semanage library
  block:
    - ansible.builtin.include_tasks: gather.yml

    - name: Perform python semanage setup
      block:
        - ansible.builtin.include_tasks: factory.yml
          when: python_semanage_is_factory_python

        - ansible.builtin.include_tasks: custom.yml
          when: not python_semanage_is_factory_python
      vars:
        python_semanage_is_factory_python: >-
          {{ python_semanage_python_check_result.stdout
             is search("/usr/bin/python3") }}
             or python_semanage_python_check_result.stdout
                is search("/usr/libexec/platform-python3")
  tags:
    - role::python_semanage
