---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Check semanage library
      command: >-
        {{ ansible_facts.python.executable }}
        - c "import semanage"
      changed_when: no
